language: node_js

node_js:
  - "6.1"

services:
  - mysql

sudo: true

before_install:
  - pip install --user awscli

install:
  - npm install
  - npm install --only=dev

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database dev_portal_test;'
  - mysql -e "create user 'dev_portal_test'@'localhost' identified by 'dev_portal_pass'; grant all privileges on dev_portal_test. * to 'dev_portal_test'@'localhost';" -uroot
  - env SERVICE_NAME=dev-portal-ci-$TRAVIS_BUILD_NUMBER make

after_script:
  - make remove
