sudo: true
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build

script:
  - docker-composer run deploy-test

deploy:
  provider: script
  script: docker -v &&
    docker-compose -v &&
    docker-compose build &&
    docker-composer run deploy-production
  on:
    tags: true