language: node_js

node_js:
  - "6.1"

services:
  - mysql

sudo: true

before_install:
  - pip install --user awscli
  - npm install -g yarn

install:
  - yarn install

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database dev_portal_test;'
  - mysql -e "create user 'dev_portal_test'@'localhost' identified by 'dev_portal_pass'; grant all privileges on dev_portal_test. * to 'dev_portal_test'@'localhost';" -uroot
  - npm install serverless@1.0.3 -g
  - node ./scripts/create-env.js ./env.yml
  - travis_wait 30 sls deploy
