sudo: true
language: bash
services:
  - mysql
  - docker
branches:
  only:
  - master

# $ENV_SETTING is either TEST or DEPLOY
before_script:
  - node ./scripts/create-env.js ./env.yml $ENV_SETTING
  - docker -v
  - docker build -t keboola/developer-portal .
  - docker run --rm -i -e AWS_ACCESS_KEY_ID=$TEST_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$TEST_AWS_SECRET_ACCESS_KEY keboola/developer-portal

script:
  - mocha --timeout 0 test

deploy:
  provider: script
  script: docker run --rm -i -e AWS_ACCESS_KEY_ID=$DEPLOY_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$DEPLOY_AWS_SECRET_ACCESS_KEY keboola/developer-portal
  on:
    tags: true