sudo: true
language: node_js
node_js:
  - "6.1"
services:
  - mysql
  - docker

# $ENV_SETTING is either TEST or DEPLOY
before_script:
  - node ./scripts/create-env.js ./env.yml TEST
  - docker -v
  - docker build -t keboola/developer-portal .
  - docker run --rm -i -e AWS_ACCESS_KEY_ID=$TEST_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$TEST_AWS_SECRET_ACCESS_KEY keboola/developer-portal

script:
  - env AWS_ACCESS_KEY_ID=$TEST_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TEST_AWS_SECRET_ACCESS_KEY mocha --timeout 0 test/functional

deploy:
  provider: script
  script: npm install && node ./scripts/create-env.js ./env.yml DEPLOY && docker -v &&  docker build -t keboola/developer-portal . && docker run --rm -i -e AWS_ACCESS_KEY_ID=$DEPLOY_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$DEPLOY_AWS_SECRET_ACCESS_KEY keboola/developer-portal
  on:
    tags: true