sudo: true
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build

script:
  - docker-compose run lint
  - docker-compose run ci-test-unit
  - docker-compose run deploy-testing
  - docker-compose run ci-test-functional


deploy:
  provider: script
  script: docker -v &&
    docker-compose -v &&
    docker-compose build &&
    docker-compose run deploy-production
  on:
    tags: true