---
custom:
  webpackIncludeModules: true
  cognitoPoolArn: "arn:aws:cognito-idp:${file(./env.yml):REGION}:${file(./env.yml):ACCOUNT_ID}:userpool/${file(./env.yml):COGNITO_POOL_ID}"
  cognitoAuthorizer:
    arn: ${self:custom.cognitoPoolArn}
  logSubscriptionFunction: logger

service: "${file(./env.yml):SERVICE_NAME}"

plugins:
  - db-migration
  #- log-subscription
  - serverless-webpack

package:
  exclude:
    - package.json
  include:
    - lib
    - node_modules
    - .env

provider:
  name: aws
  region: ${file(./env.yml):REGION}
  stage: ${file(./env.yml):STAGE}
  profile: ${file(./env.yml):PROFILE}
  runtime: nodejs4.3
  memory: 256
  timeout: 30
  versionFunctions: false
  environment: ${file(./env.yml)}
  role: developerPortalLambdaRole
  vpc:
    securityGroupIds:
      - ${file(./env.yml):VPC_SECURITY_GROUP}
    subnetIds:
      - ${file(./env.yml):VPC_SUBNET1}
      - ${file(./env.yml):VPC_SUBNET2}
  stackTags:
    KeboolaStack: "developer-portal"

functions:
  # Service
  logger:
      handler: logger.handler

  # Common
  landingPage:
    handler: public.landing
    events:
      -
        http:
          method: get
          path: "/"
  notFoundPage:
    handler: public.notFound
    events:
      -
        http:
          method: get
          path: "{anything}"
      -
        http:
          method: post
          path: "{anything}"
      -
        http:
          method: put
          path: "{anything}"
      -
        http:
          method: patch
          path: "{anything}"

  # Admin
  adminAppsApprove:
    handler: admin.appApprove
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/apps/{id}/approve"
  adminAppsDetail:
    handler: admin.appsDetail
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/apps/{id}"
  adminAppsList:
    handler: admin.apps
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/apps"
  adminAppsUpdate:
    handler: admin.appsUpdate
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: patch
          path: "admin/apps/{id}"
  adminUsersList:
    handler: admin.users
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/users"
  adminUsersMakeAdmin:
    handler: admin.userMakeAdmin
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/users/{email}/admin"
  adminUsersAddVendor:
    handler: admin.userAddVendor
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/users/{email}/vendors/{vendor}"
  adminUsersEnable:
    handler: admin.userEnable
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/users/{email}/enable"
  adminVendorsCreate:
    handler: admin.vendorsCreate
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/vendors"

  # Apps management
  appsIconsLinks:
    handler: vendor-apps-icons.links
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "apps/{vendor}/{app}/icons"
  appsIconsUpload:
    handler: vendor-apps-icons.upload
    events:
      -
        s3:
          bucket: "${file(./env.yml):S3_BUCKET}"
          event: "s3:ObjectCreated:Put"
          suffix: .png
  appsUpdate:
    handler: vendor-apps-update.appsUpdate
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: patch
          path: "apps/{vendor}/{app}"
  appsVersionsList:
    handler: vendor-apps-versions.list
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "/apps/{vendor}/{app}/versions"
  appsVersionsRollback:
    handler: vendor-apps-versions.rollback
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "apps/{vendor}/{app}/versions/{version}/rollback"
  vendorsAppsApprove:
    handler: vendor-apps-approve.handler
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps/{app}/approve"
  vendorsAppsCreate:
    handler: vendor-apps-update.appsCreate
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps"
  vendorsAppsDetail:
    handler: vendor-apps-list.appsDetail
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps/{app}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "/apps/{vendor}/{app}/versions/{version}"
  vendorsAppsList:
    handler: vendor-apps-list.appsList
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps"
  vendorAppsRepositoryCreate:
    handler: vendor-apps-repository.create
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "apps/{vendor}/{app}/repository"
  vendorAppsRepositoryGet:
    handler: vendor-apps-repository.get
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "apps/{vendor}/{app}/repository"

  # Auth
  authEmailTrigger:
    handler: auth-email.emailTrigger
  authConfirmPost:
    handler: auth.confirmPost
    events:
      -
        http:
          method: post
          path: "auth/confirm/{email}/{code}"
  authConfirmGet:
    handler: auth.confirmGet
    events:
      -
        http:
          method: get
          path: "auth/confirm/{email}/{code}"
  authConfirmResend:
    handler: auth.confirmResend
    events:
      -
        http:
          method: post
          path: "auth/confirm"
  authForgot:
    handler: auth.forgot
    events:
      -
        http:
          method: post
          path: "auth/forgot/{email}"
  authForgotConfirm:
    handler: auth.forgotConfirm
    events:
      -
        http:
          method: post
          path: "auth/forgot/{email}/confirm"
  authJoinVendor:
    handler: auth.joinVendor
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "auth/vendors/{vendor}"
  authLogin:
    handler: auth.login
    events:
      -
        http:
          method: post
          path: "auth/login"
  authProfile:
    handler: auth.profile
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "auth/profile"
  authSignup:
    handler: auth.signup
    events:
      -
        http:
          method: post
          path: "auth/signup"

  # Public
  appsDetail:
    handler: public.detail
    events:
      -
        http:
          method: get
          path: "apps/{vendor}/{app}"
  appsList:
    handler: public.list
    events:
      -
        http:
          method: get
          path: "apps"
  vendorsList:
    handler: public.vendorsList
    events:
      -
        http:
          method: get
          path: "vendors"
  vendorDetail:
    handler: public.vendorDetail
    events:
      -
        http:
          method: get
          path: "vendors/{vendor}"
  stacksList:
    handler: public.stacksList
    events:
      -
        http:
          method: get
          path: "stacks"

resources:
  Resources:
    developerPortalLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${file(./env.yml):SERVICE_NAME}-lambda-role"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: "${file(./env.yml):SERVICE_NAME}-lambda-policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:${file(./env.yml):REGION}:${file(./env.yml):ACCOUNT_ID}:log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - "s3:*"
                  Resource:
                    - "arn:aws:s3:::${file(./env.yml):S3_BUCKET}/*"
                - Effect: Allow
                  Action:
                    - "cognito-identity:*"
                    - "cognito-idp:*"
                  Resource:
                    - ${self:custom.cognitoPoolArn}
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ses:SendEmail
                    - iam:CreateRole
                    - iam:PutRolePolicy
                    - ecr:*
                    - sts:AssumeRole
                  Resource: "*"
    developerPortalEcrRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${file(./env.yml):SERVICE_NAME}-ecr-role"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  - "*"
              Action: sts:AssumeRole
        Policies:
          - PolicyName: "${file(./env.yml):SERVICE_NAME}-ecr-policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:*
                  Resource: "*"
    Rds:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: "5"
        DBName: "${file(./env.yml):RDS_DATABASE}"
        DBInstanceIdentifier: "${file(./env.yml):SERVICE_NAME}-rds"
        DBInstanceClass: "${file(./env.yml):RDS_INSTANCE_CLASS}"
        Engine: "mysql"
        EngineVersion: "5.7"
        MasterUsername: "${file(./env.yml):RDS_USER}"
        MasterUserPassword: "${file(./env.yml):RDS_PASSWORD}"
        MultiAZ: "true"
        PubliclyAccessible: "true"
        DBSubnetGroupName: "${file(./env.yml):RDS_SUBNET_GROUP}"
        VPCSecurityGroups:
          - ${file(./env.yml):VPC_SECURITY_GROUP}
    CloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            -
              DomainName: ${file(./env.yml):S3_BUCKET}.s3.amazonaws.com
              Id: "S3-${file(./env.yml):S3_BUCKET}"
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: "true"
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: "S3-${file(./env.yml):S3_BUCKET}"
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: https-only
          ViewerCertificate:
            CloudFrontDefaultCertificate: "true"
  Outputs:
    RdsUri:
      Description: "RDS Endpoint"
      Value:
        "Fn::GetAtt": ["Rds", "Endpoint.Address"]
    RdsPort:
      Description: "RDS Port"
      Value:
        "Fn::GetAtt": ["Rds", "Endpoint.Port"]
    CloudFrontUri:
      Description: "CloudFront Uri"
      Value:
        "Fn::GetAtt": ["CloudFront", "DomainName"]
