service: "${env:SERVICE_NAME}"

custom:
  webpackIncludeModules: true
  cognitoPoolArn: "arn:aws:cognito-idp:${env:REGION}:${env:ACCOUNT_ID}:userpool/${env:COGNITO_POOL_ID}"
  cognitoAuthorizer:
    arn: ${self:custom.cognitoPoolArn}
  logSubscriptionFunction: logger

plugins:
  - db-migration
  - log-subscription
  - serverless-webpack

package:
  exclude:
    - package.json
  include:
    - lib
    - node_modules
    - .env

provider:
  name: aws
  region: ${env:REGION}
  stage: ${env:STAGE}
  runtime: nodejs6.10
  memorySize: 256
  timeout: 30
  versionFunctions: false
  environment:
    SERVICE_NAME: ${env:SERVICE_NAME}
    REGION: ${env:REGION}
    STAGE: ${env:STAGE}
    SES_EMAIL_FROM: ${env:SES_EMAIL_FROM}
    RDS_DATABASE: ${env:RDS_DATABASE}
    RDS_USER: ${env:RDS_USER}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_HOST: ${env:RDS_HOST}
    RDS_PORT: ${env:RDS_PORT}
    RDS_SSL: ${env:RDS_SSL}
    S3_BUCKET: ${env:S3_BUCKET}
    LOG_HOST: ${env:LOG_HOST}
    LOG_PORT: ${env:LOG_PORT}
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    COGNITO_POOL_ID: ${env:COGNITO_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    CLOUDFRONT_URI: ${env:CLOUDFRONT_URI}
    API_ENDPOINT: ${env:API_ENDPOINT}
  role: developerPortalLambdaRole
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP}
    subnetIds:
      - ${env:VPC_SUBNET1}
      - ${env:VPC_SUBNET2}
  stackTags:
    KeboolaStack: ${env:KEBOOLA_STACK}
  stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Condition:
        StringEquals:
          ResourceType:
            - AWS::RDS::DBInstance

functions:

  logger:
      handler: logger.handler
      tags:
        KeboolaStack: ${env:KEBOOLA_STACK}

  dbMigration:
      timeout: 300
      handler: dbMigration.handler
      tags:
        KeboolaStack: ${env:KEBOOLA_STACK}

  public:
    handler: public.public
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        http:
          method: get
          path: "/"
      -
        http:
          method: get
          path: "apps/{vendorOrApp}"
      -
        http:
          method: get
          path: "apps/{vendorOrApp}/{app}"
      -
        http:
          method: get
          path: "apps"
      -
        http:
          method: get
          path: "stacks"
      -
        http:
          method: get
          path: "vendors"
      -
        http:
          method: get
          path: "vendors/{vendor}"
      -
        schedule:
          rate: rate(15 minutes)
          enabled: ${env:WARMUP_ENABLED}
      -
        http:
          method: get
          path: "{anything}"
      -
        http:
          method: post
          path: "{anything}"
      -
        http:
          method: put
          path: "{anything}"
      -
        http:
          method: patch
          path: "{anything}"

  admin:
    handler: admin.admin
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/apps/{id}/approve"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/apps/{id}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/apps"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: patch
          path: "admin/apps/{id}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/users"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/users/{email}/admin"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/users/{email}/vendors/{vendor}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: delete
          path: "admin/users/{email}/vendors/{vendor}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/vendors"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "admin/vendors/{vendor}/approve"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "admin/changes"

  apps:
    handler: apps.apps
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps/{app}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: delete
          path: "vendors/{vendor}/apps/{app}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: patch
          path: "vendors/{vendor}/apps/{app}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps/{app}/approve"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps/{app}/versions"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps/{app}/versions/{version}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps/{app}/versions/{version}/rollback"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps/{app}/icon"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/apps/{app}/repository"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/apps/{app}/deprecate"

  vendors:
    handler: vendors.vendors
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/users"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/invitations/{email}"
      -
        http:
          method: get
          path: "vendors/{vendor}/invitations/{email}/{code}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "vendors/{vendor}/users"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: delete
          path: "vendors/{vendor}/users/{email}"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "vendors/{vendor}/credentials"

  iconUpload:
    handler: iconUpload.upload
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        s3:
          bucket: "${env:S3_BUCKET}"
          event: "s3:ObjectCreated:Put"
          suffix: .png

  authEmailTrigger:
    handler: authEmail.emails
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}

  auth:
    handler: auth.auth
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        http:
          method: post
          path: "auth/login"
      -
        http:
          method: post
          path: "auth/logout"
      -
        http:
          method: get
          path: "auth/token"
      -
        http:
          method: post
          path: "auth/forgot/{email}"
      -
        http:
          method: post
          path: "auth/forgot/{email}/confirm"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: get
          path: "auth/profile"
      -
        http:
          method: post
          path: "auth/signup"
      -
        http:
          method: post
          path: "auth/confirm/{email}/{code}"
      -
        http:
          method: get
          path: "auth/confirm/{email}/{code}"
      -
        http:
          method: post
          path: "auth/confirm"
      -
        http:
          authorizer: ${self:custom.cognitoAuthorizer}
          method: post
          path: "auth/mfa/{phone}"
      -
        http:
          method: post
          path: "auth/mfa/confirm/{code}"


resources:
  Resources:
    developerPortalLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${env:SERVICE_NAME}-lambda-role"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
        Policies:
          - PolicyName: "${env:SERVICE_NAME}-lambda-policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:${env:REGION}:${env:ACCOUNT_ID}:log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - "s3:*"
                  Resource:
                    - "arn:aws:s3:::${env:S3_BUCKET}/*"
                - Effect: Allow
                  Action:
                    - "cognito-identity:*"
                    - "cognito-idp:*"
                  Resource:
                    - ${self:custom.cognitoPoolArn}
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ses:SendEmail
                    - iam:CreateRole
                    - iam:PutRolePolicy
                    - ecr:*
                    - sts:AssumeRole
                  Resource: "*"
    SMSRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${env:SERVICE_NAME}-sms-role"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: cognito-idp.amazonaws.com
              Action: sts:AssumeRole
              Condition:
                StringEquals:
                  sts:ExternalId: ${env:SERVICE_NAME}
        Policies:
          - PolicyName: "${env:SERVICE_NAME}-sms-policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: sns:publish
                  Resource: "*"
    developerPortalEcrRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${env:SERVICE_NAME}-ecr-role"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: ${env:ACCOUNT_ID}
              Action: sts:AssumeRole
        Policies:
          - PolicyName: "${env:SERVICE_NAME}-ecr-policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:*
                  Resource: "*"
    Rds:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: "5"
        DBName: "${env:RDS_DATABASE}"
        DBInstanceIdentifier: "${env:SERVICE_NAME}-rds"
        DBInstanceClass: "${env:RDS_INSTANCE_CLASS}"
        Engine: "mysql"
        EngineVersion: "5.7"
        MasterUsername: "${env:RDS_USER}"
        MasterUserPassword: "${env:RDS_PASSWORD}"
        MultiAZ: "true"
        PubliclyAccessible: "false"
        DBSubnetGroupName: "${env:RDS_SUBNET_GROUP}"
        VPCSecurityGroups:
          - ${env:RDS_SECURITY_GROUP}
        Tags:
          -
            Key: KeboolaStack
            Value: ${env:KEBOOLA_STACK}
    CloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            -
              DomainName: ${env:S3_BUCKET}.s3.amazonaws.com
              Id: "S3-${env:S3_BUCKET}"
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: "true"
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: "S3-${env:S3_BUCKET}"
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: https-only
          ViewerCertificate:
            CloudFrontDefaultCertificate: "true"
  Outputs:
    RdsUri:
      Description: "RDS Endpoint"
      Value:
        "Fn::GetAtt": ["Rds", "Endpoint.Address"]
    RdsPort:
      Description: "RDS Port"
      Value:
        "Fn::GetAtt": ["Rds", "Endpoint.Port"]
    CloudFrontUri:
      Description: "CloudFront Uri"
      Value:
        "Fn::GetAtt": ["CloudFront", "DomainName"]
    SMSRoleArn:
      Description: "SMS Role Arn"
      Value:
        "Fn::GetAtt": ["SMSRole", "Arn"]