service: developer-portal-auth

provider: aws

defaults:
  stage: dev
  region: us-east-1
  timeout: 30
  memory: 256

include:
  - lib
  - node_modules
exclude:
  - package.json

environment:
  AWS_ACCOUNT_ID: ${awsAccountId}
  COGNITO_IDENTITY_POOL_ID: ${cognitoIdentityPoolId}
  COGNITO_DEVELOPER_PROVIDER_NAME: ${cognitoDeveloperProviderName
  JWT_SECRET: ${jwtSecret}

functions:
  login:
    handler: auth.login
    events:
      - http: POST auth/login
  profile:
    handler: auth.profile
    events:
      - http: GET auth/profile
  signup:
    handler: auth.signup
    events:
      - http: POST auth/signup